name: hendrik schaefer
favicon: null
layout_spectrum: 0.65527
typography_spectrum: 0.23672
title: home
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#6cdc33'
    - '#528c6d'
    - '#272727'
    - '#ed3333'
  brandStrength: 0.5
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
